package governmentsystem;

import java.util.*;
import java.util.logging.*;
import javax.swing.*;

public class Register extends javax.swing.JFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();

        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnRegister = new java.awt.Button();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pTxtPassword = new javax.swing.JPasswordField();
        rBtnDepEd = new javax.swing.JRadioButton();
        rBtnDoJ = new javax.swing.JRadioButton();
        rBtnPNP = new javax.swing.JRadioButton();
        btnBack = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Register");
        setResizable(false);

        btnRegister.setLabel("Register");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel1.setText("First Name: ");

        jLabel2.setText("Last Name: ");

        jLabel3.setText("Password: ");

        pTxtPassword.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        buttonGroup1.add(rBtnDepEd);
        rBtnDepEd.setText("Department of Education");

        buttonGroup1.add(rBtnDoJ);
        rBtnDoJ.setText("Department of Justice");

        buttonGroup1.add(rBtnPNP);
        rBtnPNP.setText("Philippine National Police");

        btnBack.setLabel("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pTxtPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(rBtnDepEd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBtnDoJ, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rBtnPNP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(50, 50, 50))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(5, 5, 5)
                        .addComponent(pTxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25)
                        .addComponent(rBtnDepEd)
                        .addGap(10, 10, 10)
                        .addComponent(rBtnDoJ)
                        .addGap(10, 10, 10)
                        .addComponent(rBtnPNP)
                        .addGap(20, 20, 20)
                        .addComponent(btnRegister, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        String firstName = txtFirstName.getText().trim();
        String lastName = txtLastName.getText().trim();
        String password = String.valueOf(pTxtPassword.getPassword());
        String userType = "";

        String[][] userInfo = null;
        if (rBtnDepEd.isSelected()) {
            userInfo = Main.depEpUserInfo;
            userType = "depEd";
        } else if (rBtnDoJ.isSelected()) {
            userInfo = Main.doJUserInfo;
            userType = "doJ";
        } else if (rBtnPNP.isSelected()) {
            userInfo = Main.pnpUserInfo;
            userType = "pnp";
        }

        if (firstName.equals("") || lastName.equals("") || password.equals("") || (!rBtnDepEd.isSelected() && !rBtnDoJ.isSelected() && !rBtnPNP.isSelected())) {
            JOptionPane.showMessageDialog(null, "Please fill up all fields", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (firstName.toLowerCase().equals("null") || lastName.equals("null") || password.toLowerCase().equals("null")) {
            JOptionPane.showMessageDialog(null, "Invalid keyword: \"null\"", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (firstName.contains(",") || lastName.contains(",") || password.contains(",")) {
            JOptionPane.showMessageDialog(null, "Invalid character: \",\"", "Error", JOptionPane.WARNING_MESSAGE);
        } else if (Arrays.stream(userInfo[0]).allMatch(Objects::nonNull)) {
            JOptionPane.showMessageDialog(null, "Account creation has reached its storage limit", "Error", JOptionPane.WARNING_MESSAGE);
        } else {

            for (int i = 0; i < userInfo[0].length; i++) {
                if (firstName.equals(userInfo[0][i]) && lastName.equals(userInfo[1][i])) {
                    JOptionPane.showMessageDialog(null, "User is already registered", "Error", JOptionPane.WARNING_MESSAGE);
                    break;
                } else if (userInfo[0][i] == null) {

                    switch (userType) {
                        case "depEd":
                            Main.depEpUserInfo[0][i] = firstName;
                            Main.depEpUserInfo[1][i] = lastName;
                            Main.depEpUserInfo[2][i] = password;
                            JOptionPane.showMessageDialog(null, "You have been registered to Department of Education!", "Registered", JOptionPane.INFORMATION_MESSAGE);
                            break;
                        case "doJ":
                            Main.doJUserInfo[0][i] = firstName;
                            Main.doJUserInfo[1][i] = lastName;
                            Main.doJUserInfo[2][i] = password;
                            JOptionPane.showMessageDialog(null, "You have been registered to Department of Justice!", "Registered", JOptionPane.INFORMATION_MESSAGE);
                            break;
                        case "pnp":
                            Main.pnpUserInfo[0][i] = firstName;
                            Main.pnpUserInfo[1][i] = lastName;
                            Main.pnpUserInfo[2][i] = password;
                            JOptionPane.showMessageDialog(null, "You have been registered to Philippine National Police!", "Registered", JOptionPane.INFORMATION_MESSAGE);
                            break;
                    }

                    Main.indexOfAccount = i;

                    try {
                        Main.createUserInfo(userType);
                    } catch (Exception ex) {
                        Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    Main.uType = userType;
                    Main.userName = firstName + " " + lastName;
                    new UserAccount().setVisible(true);
                    this.dispose();
                    break;
                }
            }
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnBack;
    private java.awt.Button btnRegister;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField pTxtPassword;
    private javax.swing.JRadioButton rBtnDepEd;
    private javax.swing.JRadioButton rBtnDoJ;
    private javax.swing.JRadioButton rBtnPNP;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    // End of variables declaration//GEN-END:variables
}
